from .cálculo import *
from .bissexto import *
from .idade import *
from .soma_idade import *
from .ordenagem import *
from .maça import *
from .aprovação import *
from .tempo_passado import *
from .Utils import *
